#!/usr/bin/env bash

ENV_FILE="$HOME/.config/.env"

if [[ -e "$ENV_FILE" ]]; then
  source "$HOME/.config/.env"
else
  echo "File '$ENV_FILE' does not exist."
  exit 1
fi

if [[ -z $CONTEXT7_API_KEY ]]; then
  echo "Could not read Context7 API key. Please set it first."
fi

claude mcp add --transport http context7 https://mcp.context7.com/mcp \
  --header "CONTEXT7_API_KEY: $CONTEXT7_API_KEY"
