#!/usr/bin/env bash

# Note: this file is for tools that should be installed only once;
# see also './.setup/packages',

sudo apt update

curl -f https://zed.dev/install.sh | sh
curl -LsSf https://astral.sh/uv/install.sh | sh
curl -fsSL https://claude.ai/install.sh | bash
