#!/usr/bin/env bash

url=$(gum input --placeholder="Paste remote Git url..." --strip-ansi)

if [[ -n $url ]]; then
  git clone "$url" ~/coding/"$(basename "$url" .git)"
fi

echo
echo "[Press Enter to close]"
read -r
