set -g mouse on
set -s set-clipboard on
set -g focus-events on

bind -T copy-mode-vi WheelUpPane send -N 1 -X scroll-up
bind -T copy-mode-vi WheelDownPane send -N 1 -X scroll-down

set-option -as terminal-overrides ",xterm*:Ms=\\E]52;c%p1%.0s;%p2%s\\7"
set-option -as terminal-overrides ",tmux*:Ms=\\E]52;c%p1%.0s;%p2%s\\7
